package org.apache.flink.fs.ddb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "")
public class FileMeta {
    private String filename;
    private String dataId;

    public FileMeta() {
    }

    public FileMeta(String filename) {
        this.filename = filename;
    }

    public FileMeta(String filename, String dataId) {
        this.filename = filename;
        this.dataId = dataId;
    }

    @DynamoDBHashKey
    public String getFilename() {
        return filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute
    public String getDataId() {
        return dataId;
    }

    public void setDataId(String dataId) {
        this.dataId = dataId;
    }
}
